### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by joelRedPost** [lsacher/Prestashop-Shipping-Quote#3]
hi, im somehow confused with your plugin and readme doesn't really help alot, so you can provide a documentation?
tnx

**Comment by lsacher** [comment]
Sorry, but that's all the documentation. Keep in mind that it was designed for PrestaShop 1.5.6.2 so if you are running a more current version you may have to update it.

**Comment by lsacher** [comment]
You should be able to hide the carrier, but you will need to upgrade shipping-quote to work with v1.6.1.6.  Feel free to modify the module to suit your needs. But I don't use v1.6 so I do not have any way of testing it.
